# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engage_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Engage_Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('url', models.CharField(max_length=600)),
                ('desc', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluate_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluate_Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('url', models.CharField(max_length=600)),
                ('desc', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Explain_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Explain_Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('url', models.CharField(max_length=600)),
                ('desc', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='FITB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=400)),
                ('lesson_title', models.CharField(max_length=400)),
                ('grade', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1600)),
                ('answer', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=400)),
                ('subject', models.CharField(max_length=400)),
                ('course_name', models.CharField(max_length=400)),
                ('lesson_title', models.CharField(max_length=400)),
                ('grade', models.CharField(max_length=100)),
                ('bullets', models.CharField(max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='lesson_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=400)),
                ('engage_url1', models.CharField(max_length=600)),
                ('engage_url2', models.CharField(max_length=600)),
                ('engage_img1', models.CharField(max_length=600)),
                ('engage_img2', models.CharField(max_length=600)),
                ('explain_url1', models.CharField(max_length=600)),
                ('explain_url2', models.CharField(max_length=600)),
                ('explain_url3', models.CharField(max_length=600)),
                ('explain_img1', models.CharField(max_length=600)),
                ('evaluate_url1', models.CharField(max_length=600)),
                ('evaluate_url2', models.CharField(max_length=600)),
                ('evaluate_url3', models.CharField(max_length=600)),
                ('evaluate_img1', models.CharField(max_length=600)),
                ('lesson_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_lesson_plan.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=400)),
                ('lesson_title', models.CharField(max_length=400)),
                ('grade', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1600)),
                ('optiona', models.CharField(max_length=600)),
                ('optionb', models.CharField(max_length=600)),
                ('optionc', models.CharField(max_length=600)),
                ('optiond', models.CharField(max_length=600)),
                ('correct_answer', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='explain_urls',
            name='lesson_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_lesson_plan.lesson'),
        ),
        migrations.AddField(
            model_name='explain_images',
            name='lesson_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_lesson_plan.lesson'),
        ),
        migrations.AddField(
            model_name='evaluate_urls',
            name='lesson_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_lesson_plan.lesson'),
        ),
        migrations.AddField(
            model_name='evaluate_images',
            name='lesson_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_lesson_plan.lesson'),
        ),
        migrations.AddField(
            model_name='engage_urls',
            name='lesson_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_lesson_plan.lesson'),
        ),
        migrations.AddField(
            model_name='engage_images',
            name='lesson_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_lesson_plan.lesson'),
        ),
    ]
