# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0002_document_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='engage_urls',
            name='title',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='evaluate_urls',
            name='title',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='explain_urls',
            name='title',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
