# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0003_auto_20170221_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='stage',
            field=models.IntegerField(default=0),
        ),
    ]
