# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0005_auto_20170317_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
