# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0006_lesson_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
