# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0007_auto_20170322_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=600)),
                ('content', models.TextField()),
                ('date_scraped', models.DateTimeField()),
                ('source', models.TextField()),
            ],
        ),
    ]
