# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-31 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0008_offlinedocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlinedocument',
            name='date_scraped',
        ),
    ]
