# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0008_offlinedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinedocument',
            name='meta_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offlinedocument',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offlinedocument',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offlinedocument',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offlinedocument',
            name='date_scraped',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 3, 16, 36, 16, 11681)),
        ),
    ]
