# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0009_auto_20170403_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinedocument',
            name='phase',
            field=models.CharField(choices=[(b'EN', b'Engage'), (b'EV', b'Evaluate')], default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offlinedocument',
            name='date_scraped',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 14, 16, 40, 59, 178171)),
        ),
    ]
