# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 16:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0009_auto_20170403_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluate_urls',
            name='display_url',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='explain_urls',
            name='display_url',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluate_urls',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='explain_urls',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='offlinedocument',
            name='date_scraped',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 12, 16, 40, 8, 638204)),
        ),
    ]
