# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 15:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0009_auto_20170403_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinedocument',
            name='index_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offlinedocument',
            name='date_scraped',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 10, 15, 34, 18, 951302)),
        ),
    ]
