# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0010_auto_20170414_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinedocument',
            name='date_scraped',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 14, 17, 0, 34, 517096)),
        ),
        migrations.AlterField(
            model_name='offlinedocument',
            name='link',
            field=models.CharField(max_length=600, unique=True),
        ),
    ]
