# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 16:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0010_auto_20170412_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='engage_urls',
            name='display_url',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offlinedocument',
            name='date_scraped',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 12, 16, 55, 24, 450332)),
        ),
    ]
