# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0010_auto_20170410_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinedocument',
            name='date_scraped',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 10, 15, 50, 43, 749674)),
        ),
    ]
