# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0011_auto_20170414_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinedocument',
            name='date_scraped',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
