# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0012_auto_20170414_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinedocument',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=b'documents'),
        ),
    ]
