# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0013_offlinedocument_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='engage_urls',
            name='display_url',
            field=models.TextField(default=b'blank'),
        ),
        migrations.AddField(
            model_name='evaluate_urls',
            name='display_url',
            field=models.TextField(default=b'blank'),
        ),
        migrations.AddField(
            model_name='explain_urls',
            name='display_url',
            field=models.TextField(default=b'blank'),
        ),
        migrations.AlterField(
            model_name='evaluate_urls',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='explain_urls',
            name='url',
            field=models.TextField(),
        ),
    ]
