# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0014_auto_20170523_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create_lesson_plan.lesson'),
        ),
    ]
