# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0015_mcq_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='lesson_title',
        ),
    ]
