# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-06 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0018_auto_20170828_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinedocument',
            name='content_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
