# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-24 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0019_indexdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=400)),
                ('eng_url_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_lesson_plan.Engage_Urls')),
                ('eva_url_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_lesson_plan.Evaluate_Urls')),
                ('lesson_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_lesson_plan.lesson')),
            ],
        ),
    ]
