# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lesson_plan', '0020_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='user_study_link',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
    ]
